src/App.tsx, src/GenearatePDF/GeneratePDF.tsx, src/ToolsNav/ToolsNav.tsx
=> Add images to pdf with @mkhatib

src/CreatePhotosSlideshow/CreatePhotosSlideshow.tsx
When using the [Photos Slideshow] tool I'm not able to add new photos into the slides because of some issue with the state, this should fix it.
=> [Photos Slideshow] Fix issue with adding new photos

src/QuickSignPDF/QuickSignPDF.tsx
To reproduce : 
- Add new file with 2 pages
- Go to page number 2
- Click add new file
- Upload a new pdf file with 1 page
Current :
The app crashes and never responds
expected : 
To add the new file and go to page 1 without any errors
=> [Quick Sign] Fix adding new files

src/QuickSignPDF/QuickSignPDF.tsx
=> [QuickSignPDF] Allow editing annotations after download

src/PDFViewer/FabricPagePreview.tsx, src/QuickSignPDF/QuickSignPDF.tsx
=> [QuickSignPDF] Allow increasing/decreasing page sizes

src/BulkEditPhotos/BulkEditPhotos.tsx, src/images/ImageCanvasEditor.tsx
=> [BulkEditPhotos] Add adjustment sliders for brightness, contrast, saturation and others

src/BulkEditPhotos/BulkEditPhotos.tsx, src/images/ImageCanvasEditor.tsx, src/images/PhotoCropper.tsx
=> [BulkEditPhotos] Add preview size controls

src/QuickSignPDF/QuickSignPDF.tsx
=> [QuickSign] Add pdf image preview

src/BulkEditPhotos/BulkEditPhotos.tsx, src/images/PhotoCropper.tsx, src/images/defaults.tsx
=> [BulkEditPhotos] Double Click to Reset adjustment values

src/BulkEditPhotos/BulkEditPhotos.tsx, src/images/PhotoCropper.tsx, src/images/defaults.tsx
=> [BulkEditPhotos] Add popular social crop sizes

src/QuickSignPDF/QuickSignPDF.tsx, src/ui/ColorPickerButton.tsx
=> [QuickSignPDF] Add Font and Stroke Sizes and Colors

src/BulkEditPhotos/BulkEditPhotos.tsx, src/images/ImageCanvasEditor.tsx, src/images/defaults.tsx
=> [BulkEditPhotos] Add frame color picker and fix color adjustment

src/BulkEditPhotos/BulkEditPhotos.tsx, src/CreatePhotosSlideshow/CreatePhotosSlideshow.tsx, src/QuickSignPDF/QuickSignPDF.tsx, src/images/defaults.tsx, src/ui/ColorPickerButton.tsx
=> [QuickSignPDF][BulkEditPhotos] Add alpha support to colors

src/QuickSignPDF/QuickSignPDF.tsx, src/ToolsNav/ToolsNav.tsx
=> [QuickSignPDF] Add a quick date button

src/CreatePhotosSlideshow/CreatePhotosSlideshow.tsx
=> [CreatePhotosSlideshow] Fix image re-order

src/App.tsx, src/CreateMeme/CreateMeme.tsx, src/ToolsNav/ToolsNav.tsx
These are just basic functionalities for the tool, stuff like text color, size, position, presets meme etc .. can be added separately. Features to add for the tool can be added in this issue #81
closes #70
=> [CreateMeme] Add Basic functionalities

src/QuickSignPDF/QuickSignPDF.tsx
=> [QuickSignPDF] Offset path to 0,0 and use left/top to position it

package.json, src/QuickSignPDF/QuickSignPDF.tsx, src/ui/ImagePickerButton.tsx, yarn.lock
=> [QuickSignPDF] Fix positioning a bit more and Add save Objects

package.json, src/CreateMeme/CreateMeme.tsx, src/QuickSignPDF/QuickSignPDF.tsx, src/useCanvasKeybindings.tsx, yarn.lock
=> Add keyup for select/deselect

src/QuickSignPDF/QuickSignPDF.tsx
=> [QuickSign] Fix save selection issues

src/Home/Home.tsx, src/ToolsNav/ToolsNav.tsx, src/assets/tailwind.css
=> Change styling
